Sprint 6 solution
m1rovou/java-kanban pull request #1
Opened 2024-08-01 12:06 UTC by m1rovou

2024-08-02 06:37 UTC, VadimZharkov commented on src/managers/InMemoryTaskManager.java
> +    private final Map<Integer, Task> tasks;
Да, верно, правильная практика определять поля и переменные базовым типом

2024-08-02 06:42 UTC, VadimZharkov commented on src/managers/InMemoryHistoryManager.java
> +        head = null;
поля являющиеся ссылками на объекты инициализируются null по умолчанию.
поэтому можно сократить код, конструктор убрать, а поля определить
```
   private final Map<Integer, Node> history = new HashMap<>();
   private Node head;
   private Node tail;
```
будет тот же результат

2024-08-02 07:01 UTC, VadimZharkov commented on src/managers/Node.java
> +class Node {
Хорошо что сделал видимость на уровне пакета managers, но еще лучше Node сделать внутренним классом для InMemoryHistoryManager, т.к. он используется только в нем внутри.
У классов для внутреннего использования типа Node допускается не делать геттеров/сеттеров а использовать поля напрямую, например tail.next

2024-08-02 07:10 UTC, VadimZharkov commented on src/managers/InMemoryHistoryManager.java
> +        if (!(history.isEmpty())) {
Есть широко используемая практика написания кода, под названием "ранний выход" (early return).
Суть в том чтобы выходить из метода сразу при не соблюдении условий для дальейшего выполнения. Позволяет уменьшать количество отступов-лесенок и делает код более читабельным (заметно станет на относительно боьших методах).
В данном случае
```
public List<Task> getHistory() {
       List<Task> historyList = new ArrayList<>();
        if (history.isEmpty()) {
            return historyList;
        }
        Node node = head;
        for (int i = 0; i < history.size(); i++) {
                historyList.add(node.getData());
                node = node.getNext();
        }
        return historyList;
}
```

2024-08-02 07:12 UTC, VadimZharkov commented on src/managers/InMemoryHistoryManager.java
> +        if (task != null) {
Здесь тоже если воспользоваться ранним выходом
```
if (task == null)
    return;
...
```

2024-08-02 07:12 UTC, VadimZharkov requested changes
Можно улучшить

2024-08-03 18:09 UTC, m1rovou commented on src/managers/InMemoryHistoryManager.java
> +        if (task != null) {
Подправил. Так же в методе remove добавлен ранний выход, если узел с заданным идентификатором не найден.

2024-08-03 18:16 UTC, m1rovou commented
Все подправил!)

2024-08-04 04:58 UTC, VadimZharkov approved these changes

2024-08-04 15:03 UTC, merged